version: '3.1'
services:

  mysql:
    image: mysql:8.0-debian
    environment:  
      MYSQL_DATABASE: pathology_db  
      MYSQL_USER: pathology 
      MYSQL_PASSWORD: fdgdhdhd
      MYSQL_ROOT_PASSWORD: root   
      # MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - app-network
  
  php82:
    build: ./docker-php
    working_dir: /var/www/laravel
    volumes:
      - ./pathology-app:/var/www/laravel    
      - ./pathology-app/public:/var/www/laravel/public
      - ./pathology-app/vendor:/var/www/laravel/vendor
    # command: bash -c "php artisan serve --host=0.0.0.0 --port=8080"
    #command: bash -c "chmod 777 -R /var/www/laravel/public && chown -R www-data:www-data /var/www/laravel"
    ports:
      - 9000:9000 
    depends_on: 
      - mysql
    networks:
      - app-network 

  nginx:
    build: ./docker-nginx
    working_dir: /var/www/laravel
    volumes:
      - ./docker-nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker-nginx/log/error.log:/var/log/nginx/error.log
      #- ./docker-nginx/log/access.log:/var/log/nginx/access.log
    depends_on: 
      - php82
    ports:
      - 8080:80
    networks:
      - app-network

volumes:
    exclude_vendor:

networks:
  app-network:
    driver: bridge
    