version: '3.1'
services:

  mysql:
    image: mariadb:10.9
    environment:  
      MARIADB_DATABASE: phatology_db  
      MARIADB_USER: phatology 
      MARIADB_PASSWORD: Jko0Tr23
      MARIADB_ROOT_PASSWORD: SJhf0964R   
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - app-network
  
  php82:
    build: ./docker-php
    working_dir: /var/www/laravel
    volumes:
      - ./phatology-app:/var/www/laravel    
      - ./phatology-app/public:/var/www/laravel/public
    # command: bash -c "php artisan serve --host=0.0.0.0 --port=8080"
    #command: bash -c "chmod 777 -R /var/www/laravel/public && chown -R www-data:www-data /var/www/laravel"
    ports:
      - 9000:9000 
    depends_on: 
      - mysql
    networks:
      - app-network

  nginx:
    build: ./docker-nginx
    working_dir: /var/www/laravel
    volumes:
      - ./docker-nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker-nginx/log/error.log:/var/log/nginx/error.log
      #- ./docker-nginx/log/access.log:/var/log/nginx/access.log
    depends_on: 
      - php82
    ports:
      - 8080:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    