version: '3.0'
services:

  db:
    image: mysql:8.0-debian
    container_name: mysql8_db    
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config/:/etc/mysql/conf.d/
    environment:  
      MYSQL_DATABASE: pathology_db  
      MYSQL_USER: admin 
      MYSQL_PASSWORD: ZtFiLN9
      MYSQL_ROOT_PASSWORD: ZtFiLN9   
      # MYSQL_ALLOW_EMPTY_PASSWORD: yes    
    ports:
      - 3333:3306
    networks:
      - laravel
    restart: always
  
  app:
    # build: ./docker-php
    build:
      args:
        user: teddi
        uid: 1000
      context: ./docker-php
      dockerfile: Dockerfile
    container_name: pathology_app    
    # working_dir: /var/www/laravel
    volumes:
      - ./pathology-app:/var/www     
    ports:
      - 9000:9000 
    depends_on: 
      - db   
    networks:
      - laravel 
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_server    
    ports:
      - "88:80"
    volumes:
      - ./docker-nginx:/etc/nginx/conf.d # แนบไฟล์คอนฟิกของ Nginx ของคุณ
      - ./pathology-app/public:/var/www/public    
    networks:
      - laravel
    restart: always

networks:
  laravel:
    driver: bridge
    