version: '3.0'
services:

  db:
    image: mysql:8.0-debian
    container_name: pathology_db    
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config/:/etc/mysql/conf.d/
    environment:  
      MYSQL_DATABASE: pathology_db  
      MYSQL_USER: lab 
      MYSQL_PASSWORD: lab@11443
      MYSQL_ROOT_PASSWORD: lab@11443   
      # MYSQL_ALLOW_EMPTY_PASSWORD: yes    
    ports:
      - 3307:3306
    networks:
      - laravel
    restart: always
  
  app:    
    build:
      args:
        user: web
        uid: 1000
      context: ./docker-php
      dockerfile: Dockerfile
    container_name: pathology_app  
    volumes:
      - ./pathology-app:/var/www   
      - ./docker-php/config/:/usr/local/etc/php/conf.d/    
    depends_on: 
      - db   
    networks:
      - laravel 
    restart: always

  nginx:
    image: nginx:latest
    container_name: pathology_nginx   
    ports:
      - "8080:80"
    volumes:
      - ./docker-nginx:/etc/nginx/conf.d # แนบไฟล์คอนฟิกของ Nginx ของคุณ
      - ./pathology-app:/var/www   
    networks:
      - laravel
    restart: always

networks:
  laravel:
    driver: bridge
    