version: '3.1'
services:

  mysql:
    image: mariadb:10.9
    environment:  
      MARIADB_DATABASE: phatology_db  
      MARIADB_USER: phatology 
      MARIADB_PASSWORD: Jko0Tr23
      MARIADB_ROOT_PASSWORD: SJhf0964R   
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3333:3306
    networks:
      - app-network
  
  php82:
    build: ./docker-php
    working_dir: /var/www/laravel
    volumes:
      - ./phatology-app:/var/www/laravel    
    depends_on: 
      - mysql
    networks:
      - app-network

  nginx:
    build: ./docker-nginx
    working_dir: /var/www/laravel
    volumes:
      - ./docker-nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php82
    ports:
      - 8080:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    